food/urls.py
from django.urls import path

from . import views

app_name = 'food'
urlpatterns = [
  # /food/
  path('', views.IndexClassView.as_view(), name = 'index'),
  # /food/1
  path('<int:pk>/', views.FoodDetail.as_view(), name = 'detail'),
  # /food/add
  path('add', views.CreateItem.as_view(), name = 'create_item'),
  # /food/update/1
  path('update/<int:id>/', views.update_item, name = 'update_item'),
  # /food/delete/1
  path('delete/<int:id>/', views.delete_item, name = 'delete_item')
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as authentication_views
from django.urls import include, path
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name = 'register'),
    path('login/', authentication_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('profile/', user_views.profilepage, name =  'profile')
]

urlpatterns += [
    # ... the rest of your URLconf goes here ...
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse


# Create your models here.
class Item(models.Model):
  item_name = models.CharField(max_length = 200)
  item_desc = models.CharField(max_length = 200)
  item_price = models.IntegerField()
  item_image = models.CharField(max_length = 500, default = 'https://cdn.dribbble.com/users/1012566/screenshots/4187820/topic-2.jpg')

  def __str__(self):
    return self.item_name
  

  def get_absolute_url(self):
    return reverse('food:detail', kwargs = { 'pk': self.pk })

users/models.py
from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Profile(models.Model):

  user = models.OneToOneField(User, on_delete = models.CASCADE)
  image = models.ImageField(default = 'profilepic.png', upload_to = 'profile_pictures')
  location = models.CharField(max_length = 100)

  def __str__(self):
    return self.user.username

food/forms.py
from django import forms

from .models import Item


class ItemForm(forms.ModelForm):

  class Meta:
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RegisterForm(UserCreationForm):
  email = forms.EmailField()

  class Meta:
    model = User
    fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from .forms import ItemForm
from .models import Item


# Create your views here.
def index(request):
  item_list = Item.objects.all()

  context = {
    'item_list': item_list
  }
  
  return render(request, 'food/index.html', context)


class IndexClassView(ListView):

  model = Item
  template_name = 'food/index.html'
  context_object_name = 'item_list'


def item(request):
  return HttpResponse('<h1>This is an item view</h1>')


def detail(request, item_id):
  item = Item.objects.get(pk = item_id)

  context = {
    'item': item
  }

  return render(request, 'food/detail.html', context)


class FoodDetail(DetailView):

  model = Item
  template_name = 'food/detail.html'


def create_item(request):
  form = ItemForm(request.POST or None)

  if form.is_valid():
    form.save()

    return redirect('food:index')
  
  return render(request, 'food/item_form.html', { 'form': form })


class CreateItem(CreateView):

  model = Item
  fields = ['item_name', 'item_desc', 'item_price', 'item_image']
  template_name = 'food/item_form.html'

  def form_valid(self, form):
    form.instance.user_name = self.request.user

    return super().form_valid(form)


def update_item(request, id):
  item = Item.objects.get(id = id)
  form = ItemForm(request.POST or None, instance = item)

  if form.is_valid():
    form.save()

    return redirect('food:index')
  
  return render(request, 'food/item_form.html', { 'form': form, 'item': item })


def delete_item(request, id):
  item = Item.objects.get(id = id)

  if request.method == 'POST':
    item.delete()

    return redirect('food:index')
  
  return render(request, 'food/item_delete.html', { 'item': item })

users/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import redirect, render

from .forms import RegisterForm


# Create your views here.
def register(request):

  if request.method == 'POST':
    form = RegisterForm(request.POST)

    if form.is_valid():
      form.save()
      username = form.cleaned_data.get('username')
      messages.success(request, f'Welcome {username}. You have successfully logged in')

      return redirect('login')
  else:
    form = RegisterForm()

  return render(request, 'users/register.html', { 'form': form })


@login_required
def profilepage(request):

  return render(request, 'users/profile.html')

food/templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'food/style.css' %}">
</head>
<body>
  <nav class="navbar navbar-dark bg-dark">
    <a href="{% url 'food:index' %}" class="navbar-brand">FoodApp</a>

    <div class="navbar">
      {% if user.is_authenticated %}
        <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add item</a>
        <a href="{% url 'logout' %}" class="nav-item nav-link">Log out, {{ user.username }}</a>
        <a href="{% url 'profile' %}" class="nav-item nav-link">Profile</a>
      {% else %}
        <a href="{% url 'login' %}" class="nav-item nav-link">Log in</a>
      {% endif %}
    </div>
  </nav>

  {% if messages %}
    {%for message in messages %}
      <div class="alert alert-{{ message.tags }}">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <div class="container mt-4">

    {% block body%}
    {% endblock %}
    
  </div>

</body>
</html>

food/templates/food/detail.html
{% extends 'food/base.html' %}

{% block body %}

<div class="row">

  <div class="col-12 col-md-6">
    <img width="100%;" src="{{ object.item_image }}" alt="{{ object.item_name }}" class="card">
  </div>

  <div class="col-12 col-md-6">
    <h1>
      {{ object.item_name }}
    </h1>
    
    <h2>
      {{ object.item_desc }}
    </h2>
    
    <h3>
      ${{ object.item_price }}
    </h3>
    {% if user.is_authenticated %}
      <a href="{% url 'food:delete_item' object.id %}" class="btn btn-danger">Delete</a>
    {% endif %}
  </div>

</div>
{% endblock %}

food/templates/food/index.html
{% extends 'food/base.html' %} 

{% block body %}

  <div class="row">

      {% for item in item_list %}

      <div class="col-12 col-md-3 mt-3">
        <div class="card">
          <img src="{{ item.item_image }}" alt="{{ item.item_name }}" class="card-img-top">
          <div class="card-body">
            <h5 class="card-title">
              {{ item.item_name }}
            </h5>
            <p class="card-text">
              {{ item.item_desc }} for only ${{ item.item_price }}
            </p>
            <a href="{% url 'food:detail' item.id %}" class="btn btn-warning">Check it out!</a>
          </div><!-- end .card-body -->
        </div><!-- end .card -->
      </div><!-- end .col -->
      
      {% endfor %}

  </div>

{% endblock %}

food/templates/food/item_delete.html
{% extends 'food/base.html' %}

{% block body %}

<form method="post">
  {% csrf_token %}

  <div class="alert alert-danger" role="alert">
    Are you sure you want to delete {{ item.item_name }} ?
  </div>
  <button type="submit">Confirm</button>
</form>

{% endblock %}

food/templates/food/item_form.html
{% extends 'food/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card">
      <div class="card-header bg-info text-white">
        <div class="card-title">
          Add item
        </div>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
        
          {% for field in form %}
            <div class="form-group">
              {{ field.name | title }}
              <br>
              {{ field }}
            </div>
          {% endfor %}
        
          <button class="btn btn-info" type="submit">Add</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'food/base.html' %}

{% block body %}

<div class="row">
  <div class="col-12 col-md-4 offset-md-4">
    <div class="card">
      <div class="card-header bg-info text-white">
        <div class="card-title">
          Login
        </div>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
        
          {% for field in form %}
            <div class="form-group">
              {{ field.name | title }}:
              {{ field }}
            </div>
          {% endfor %}
        
          <button class="btn btn-info" type="submit">Login</button>
        </form>
      </div>
    </div>
  </div>
</div>


{% endblock %}

users/templates/users/logout.html
{% extends 'food/base.html' %}

{% block body %}

<h1>
  You have been logged out.
</h1>

{% endblock %}

users/templates/users/profile.html
{% extends 'food/base.html' %}

{% block body %}

<div class="row">
  <div class="col-12 col-md-3">
    <div class="card">
      <img src="{{ user.profile.image.url }}" alt="{{ user.username }}" class="card-img-top">
      <div class="card-body">
        <h5 class="card-title">
          {{ user.username }}
        </h5>
      </div><!-- end .card-body -->
    </div><!-- end .card -->
  </div><!-- end .col -->
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'food/base.html' %}

{% block body %}

<div class="row">
  <div class="col-md-4 offset-md-4">
    <div class="card">
      <div class="card-header bg-info text-white">
        <div class="card-title">
          Registration
        </div>
      </div>
      <div class="card-body">
        <form method="post">
          {% csrf_token %}
        
          {% for field in form %}
            <div class="form-group">
              {% if 'password1' == field.name %}
              Password
              {% elif 'password2' == field.name %}
              Retype password
              {% else %}
              {{ field.name | title }}
              {% endif %}
              <br>
              {{ field }}
            </div>
          {% endfor %}
        
          <button class="btn btn-info" type="submit">Sign up</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock %}